### ISSUE TITLE
Method for deleting the messages from S3?

### ISSUE THREAD

**Issue by mihai-waydev** [e0ipso/amazon-sqs-php-extended-client-lib#10]
Hi!

I saw that there was a feature where the files from S3 would be deleted at the end, but then you removed it. Can you tell me why and if there is any way to handle this part so that the bucket doesn't grow infinitely?

Thanks!

**Comment by e0ipso** [comment]
I wonder about that as well. I cannot remember about that particular change, it's been a while since I wrote this code. Do you mind tracking that change in git and linking it here?

**Comment by mihai-waydev** [comment]
This is where it got added (not sure it was completed): https://github.com/e0ipso/amazon-sqs-php-extended-client-lib/commit/9dd54447c80fb2f12004ec11f556ce38c12fa1fe

And here it got removed: https://github.com/e0ipso/amazon-sqs-php-extended-client-lib/commit/15f859e95ffa014537382c6678dc74d7069aceb8

**Comment by e0ipso** [comment]
Yeah, it looks like this was intentional. I cannot remember my reasoning back then, but it seems that I deferred to rely on auto-deletion of old objects in AWS as opposed to manually do it.

You should likely look into auto-expiration of objects in your bucket configuration.
