### ISSUE TITLE
Install via Composer fails

### ISSUE THREAD

**Issue by michaeldzjap** [e0ipso/amazon-sqs-php-extended-client-lib#7]
I am trying to install this package via Composer in a newly created Laravel 5.4 project as per the instructions in the readme, but it fails with exception:

```
[InvalidArgumentException]                                                                                                    
  Could not find package e0ipso/amazon-sqs-php-extended-client-lib at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

I see the last update was 9 months ago. Is this package still being maintained?

Thanks.

**Comment by e0ipso** [comment]
@michaeldzjap hello. This package is indeed maintained. However I can only attest to my use cases, that's why I didn't tag a stable release yet.

Did you have success trying it? Did you move to another solution?

**Comment by michaeldzjap** [comment]
Yes, I went with another solution in the end. So this issue is not relevant anymore (at least for me).

Thanks.
