### ISSUE TITLE
What's the licence ?

### ISSUE THREAD

**Issue by amoutiers** [e0ipso/amazon-sqs-php-extended-client-lib#9]
Hi,

There's no licence file in the repo, what's the licence ?

Best regards

**Comment by e0ipso** [comment]
You are correct. I will get that fixed. The license is only specified in `composer.json`. https://github.com/e0ipso/amazon-sqs-php-extended-client-lib/blob/master/composer.json#L14

I hope that works for you.

**Comment by amoutiers** [comment]
Ok thanks !

No GPLv2 is not an option for us, this licence is contaminant. We must publish all the source code, if we use your lib even for a small feature.

Have a nice day.

**Comment by e0ipso** [comment]
You might be mislead on the implications of GPL v2. You would only need to publish the source code if one were to license the derivative software. In other words, if a company plans on taking free software someone wrote for all and then sell it.

Take this as a grain of salt, I am no expert by any means. This is not legal advise.

**Comment by e0ipso** [comment]
In any case thanks for contributing to the issue queue.
